spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: registration_route
          uri: http://localhost:8082/api/v1/customers/registration
          predicates:
            - Path=/api/v1/customers/registration/**
        - id: customers_route
          uri : http://localhost:8082/api/v1/customers/{id}
          predicates:
            - Path=/api/v1/customers/{id}
          filters:
            - TokenRelay=


  security:
    oauth2:
      client:
        provider:
          keycloak-provider:
            issuer-uri: http://localhost:8090/realms/technoExpert
        registration:
          gateway-service:
            provider: keycloak-provider
            client-id: gateway-service-client
            client-secret: ng8zu3qEVsJOFwIskclhHPlL31OKm94V
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8081/login/oauth2/code/gateway-service"
            scope : openid
      auth:
        uriToken : http://localhost:8090/realms/technoExpert/protocol/openid-connect/token
        grant_type : password

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka





