spring:
  application:
    name: gateway-service
  security:
    oauth2:
      client:
        provider:
          keycloak-provider:
            issuer-uri: http://localhost:8090/realms/technoExpert
        registration:
          gateway-service:
            provider: keycloak-provider
            client-id: gateway-service-client
            client-secret: i9q5x8Yzd64FZN9W7EAiMCUVgyqk5Wfb
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8081/login/oauth2/code/gateway-service"
server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka





