spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: registration_route
          uri: http://localhost:8082/api/v1/customers/registration
          predicates:
           - Path=/api/v1/customers/registration/**
          filter:
           - TokenRelay =

  security:
    oauth2:
      client:
        provider:
          keycloak-provider:
            issuer-uri: http://localhost:8090/realms/technoExpert
        registration:
          gateway-service:
            provider: keycloak-provider
            client-id: gateway-service-client
            client-secret: i9q5x8Yzd64FZN9W7EAiMCUVgyqk5Wfb
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8081/login/oauth2/code/gateway-service"
            scope : openid



server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka





